### ISSUE TITLE
1.1.0 TODO List

### ISSUE THREAD

**Issue by nomadjimbob** [nomadjimbob/MCPEDiscordRelay#8]
This is a comprehensive TODO list that will be regularly updated. It contains what has been done and what needs to be done for the release version in the title.

Last updated: 08/05/2020 at 07:20 am

---

- [ ]  Replace CURL functions with [Guzzle library](https://github.com/guzzle/guzzle)
- [ ]  Add support for 2-way discord chat
- [ ]  Add regex option support for whitelist/blacklist relay messages
